(define (test-flnormalized-fraction-exponent)
  (test-values (flnormalized-fraction-exponent 1.0)
	       '(0.5 1))
  (test-values (flnormalized-fraction-exponent 1.5)
	       '(0.75 1))
  (test-values (flnormalized-fraction-exponent 2.0)
	       '(0.5 2))
  (test-values (flnormalized-fraction-exponent 0.5)
	       '(0.5 0))
  (test-values (flnormalized-fraction-exponent 0.25)
	       '(0.5 -1))
  (test-values (flnormalized-fraction-exponent 0.0)
	       '(0.0 0))
  (test-values (flnormalized-fraction-exponent -0.0)
	       '(-0.0 0))
  (test-assert (let-values (((fl e) (flnormalized-fraction-exponent +inf.0)))
		 (and (equal? fl (flonum +inf.0))
		      (exact-integer? e))))
  (test-assert (let-values (((fl e) (flnormalized-fraction-exponent -inf.0)))
		 (and (equal? fl (flonum -inf.0))
		      (exact-integer? e))))
  (test-assert (let-values (((fl e) (flnormalized-fraction-exponent +nan.0)))
		 (and (flnan? fl)
		      (exact-integer? e))))
  (test-values (flnormalized-fraction-exponent fl-least)
	       `(0.5 ,(+ fl-minimum-exponent 1)))
  (test-values (flnormalized-fraction-exponent fl-greatest)
	       `(,(fladjacent 1.0 -inf.0)
		 ,(+ fl-maximum-exponent 1))))


